# Generated by Django 2.1 on 2018-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flight', '0002_auto_20181002_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flghts', models.ManyToManyField(blank=True, related_name='passengers', to='flight.Flight')),
            ],
        ),
    ]
