# Generated by Django 2.1 on 2018-10-04 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flight', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flghts',
            new_name='flights',
        ),
    ]
